#!/usr/bin/env python

import rospy
import actionlib
import sys

from tiago_bartender_msgs.msg import PlacePickAction, PlacePickGoal

if __name__ == '__main__':
	rospy.init_node('test_place_pick')
	client = actionlib.SimpleActionClient('tiago_place_pick', PlacePickAction)
	client.wait_for_server()

	if(len(sys.argv) > 1):
		goal = PlacePickGoal(pick_object_id= sys.argv[1])
	else:
		goal = PlacePickGoal(pick_object_id= "tequila")

	client.send_goal(goal)
	client.wait_for_result(rospy.Duration(0.0))

	print("State:")
	print(client.get_state())
	print()
	print("Result:")
	print(client.get_result())
