#!/usr/bin/env python

import rospy
import actionlib
import sys

from tiago_bartender_msgs.msg import PlaceAction, PlaceGoal

if __name__ == '__main__':
	rospy.init_node('test_place')
	client = actionlib.SimpleActionClient('tiago_place', PlaceAction)
	client.wait_for_server()

        # TODO: define place goal
	# if(len(sys.argv) > 1):
	# 	goal = PlaceGoal(place_pose= sys.argv[1])
	# else:
	# 	goal = PlaceGoal(pick_object_id= "tequila")

        goal = PlaceGoal()
	client.send_goal(goal)
	client.wait_for_result(rospy.Duration(0.0))

	print("State:")
	print(client.get_state())
	print()
	print("Result:")
	print(client.get_result())
