#!/usr/bin/env python

from __future__ import print_function

import rospy
import actionlib
import sys

import moveit_commander

import moveit_msgs
import moveit_msgs.srv
from moveit_msgs.msg import AttachedCollisionObject, CollisionObject

if __name__ == '__main__':
    rospy.init_node('test_place')

    psi = moveit_commander.PlanningSceneInterface()

    objects = psi.get_attached_objects()

    if len(objects) > 0:
        for o in objects.keys():
            objects[o].object.operation = CollisionObject.REMOVE

        scene = moveit_msgs.msg.PlanningScene()
        scene.is_diff = True
        scene.robot_state.is_diff = True
        scene.robot_state.attached_collision_objects = objects.values()
        apply_planning_scene = rospy.ServiceProxy("apply_planning_scene", moveit_msgs.srv.ApplyPlanningScene)
        rs = apply_planning_scene.call(scene)
        print('Removed attached objects:')
        print(objects.keys())
    else:
        print('No attached objects found')
